modified (fixed) vm-script

diff --git a/roles/l_vm/tasks/main.yml b/roles/l_vm/tasks/main.yml
--- a/roles/l_vm/tasks/main.yml
+++ b/roles/l_vm/tasks/main.yml
@@ -26,7 +26,7 @@
   become: true
   shell: |
     #!/bin/bash
-    # copied from https://raw.githubusercontent.com/Microsoft/linux-vm-tools/master/ubuntu/18.04/install.sh
+    # copied (& partially modified) from https://raw.githubusercontent.com/Microsoft/linux-vm-tools/master/ubuntu/18.04/install.sh
 
     #
     # This script is for Ubuntu 18.04 Bionic Beaver to download and install XRDP+XORGXRDP via
@@ -52,11 +52,11 @@
 
     apt update && apt upgrade -y
 
-    if [ -f /var/run/reboot-required ]; then
-        echo "A reboot is required in order to proceed with the install." >&2
-        echo "Please reboot and re-run this script to finish the install." >&2
-        exit 1
-    fi
+    #if [ -f /var/run/reboot-required ]; then
+    #    echo "A reboot is required in order to proceed with the install." >&2
+    #    echo "Please reboot and re-run this script to finish the install." >&2
+    #    exit 1
+    #fi
 
     ###############################################################################
     # XRDP
